version: '3.8'

services:
  componego-framework-docs:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: componego-framework-docs
    working_dir: /docs
    volumes:
      - .:/docs:cached
    ports:
      - "8123:8123"
